### PR TITLE
[StyleCop] Fix all warnings in Japanese HolidayExtractorConfiguration

### PR DESCRIPTION
**Pull request by ceciliaavila**
- Renamed file 'HolidayExtractor' to 'JapaneseHolidayExtractorConfiguration' to match the class name.
- Fixed spacing.
- Reordered methods and properties.

### CODE REVIEW

**Review by JuanAr — CHANGES_REQUESTED** [review]
Sames as #155: Do not include new line changes.

**Comment by ceciliaavila** [comment]
It's a file renamed, that is why it looks like the entire file has been modified.

**Comment by JuanAr** [comment]
@Aliandi the original file has `CR` + `LF` as new line chars. The new one has `LF`. This is why the difference viewer shows the entire file content as changes.
You can check the line endings with a tool like Notepad++
Also, you should check you git settings for new line.

**Review by Bill7zz — COMMENTED** [review]
LGTM

**Comment by JuanAr** [comment]
@Aliandi please fix commit history

**Review by VictorGrycuk — CHANGES_REQUESTED** [review]
The PR includes changes to `ItalianTimeParserConfiguration.cs`, however there is no mention to it in the PR title nor in the title. Please mention the changes in this file.

**Comment by ceciliaavila** [comment]
> The PR includes changes to `ItalianTimeParserConfiguration.cs`, however there is no mention to it in the PR title nor in the title. Please mention the changes in this file.

This file was removed because it was already fixed in PR#1301.

**Review by VictorGrycuk — APPROVED** [review]
LGTM

**Review by JuanAr — APPROVED** [review]
👍

**Pull request closed without merging**
