### PR TITLE
[StyleCop] Fix all warnings in BaseDateParser file

### PR DESCRIPTION
**Pull request by ceciliaavila**
Renamed variable for clarity in BaseDateParser. Corresponds to feedback on PR #1266

### CODE REVIEW

**Review by Bill7zz — APPROVED** [review]
LGTM

**Review by VictorGrycuk — APPROVED** [review]
Better than the original name, but I would have dropped the `Tmp` as no other `ExtractResult` is declared in the same scope.
LGTM!

**Comment by VictorGrycuk** [comment]
@ceciliaavila Just a small thing: Instead of linking to the PR, link to the comment soliciting the change.

**Review by JuanAr — APPROVED** [review]
👍

**Pull request closed without merging**
