### PR TITLE
[Java] Choice base classes porting

### PR DESCRIPTION
**Pull request by joseques**
## Proposed Changes
- Ported Interfaces
- Ported base classes structure with methods

Test are passing (skipped) correctly after the addition of the classes
image

### CODE REVIEW

**Review by enzocano — APPROVED** [review]
LGFM

**Review by JuanAr — APPROVED** [review]
:shipit:

**Comment by JuanAr** [comment]
Can we close this one?

**Comment by joseques** [comment]
Yes, since this PR is already ported to MS I'm closing this to track the remote one.

**Pull request closed without merging**
