### PR TITLE
[StyleCop] Fix all the warnings in ChoiceExtractor

### PR DESCRIPTION
**Pull request by Aliandi**
- Add trailing coma
- Extract ChoiceExtractDataResult class
- Add spacing
- Remove parentheses

### CODE REVIEW

**Review by VictorGrycuk — APPROVED** [review]
LGTM

**Review by JuanAr — APPROVED** [review]
LGTM

**Review by ceciliaavila — APPROVED** [review]
LGTM

**Comment by ceciliaavila** [comment]
This PR was merged on PR #1339

**Pull request closed without merging**
