### PR TITLE
[StyleCop] Fix warnings in DataDrivenTest\Number

### PR DESCRIPTION
**Pull request by Bill7zz**
- Warning SA1100 Do not prefix calls with base unless local implementation exists
- Extract LongFormTestConfiguration

### CODE REVIEW

**Review by VictorGrycuk — CHANGES_REQUESTED** [review]
Other than the missing reference to the ruleset, this is good to go.

However, since this PR depends on a change made on other PR add a line in this PR details noting that this PR depends on another, with a link to said PR. Something like:
> **Note:** This PR depends on PR [#XXX](https://github.com/southworkscom/Recognizers-Text/pull/XXX). Will rebase when it is merged.

**Comment by VictorGrycuk** [comment]
@Bill7zz I would remove the list of modified files as it is redundant. I would only leave the last two lines as bullet points.

**Review by VictorGrycuk — APPROVED** [review]
LGTM 👍

**Review by JuanAr — APPROVED** [review]
👍

**Pull request closed without merging**
