### PR TITLE
[StyleCop] Fix all warnings in HolidayExtractorChs

### PR DESCRIPTION
**Pull request by ceciliaavila**
- Renamed file from `HolidayExtractorChs` to `ChineseHolidayExtractorConfiguration` to match class name.
- Fixed spacing.
- Reordered methods and properties.

### CODE REVIEW

**Review by Bill7zz — APPROVED** [review]
LGTM

**Review by VictorGrycuk — CHANGES_REQUESTED** [review]
@ceciliaavila Just a small change, could you please rephrase the first item in the PR to include the previous name? Something like:
> File `x` was renamed to `y` to match class name.

**Comment by ceciliaavila** [comment]
> @ceciliaavila Just a small change, could you please rephrase the first item in the PR to include the previous name? Something like:
> 
> > File `x` was renamed to `y` to match class name.

Done!

**Review by VictorGrycuk — APPROVED** [review]
LGTM!

**Review by JuanAr — APPROVED** [review]
👍

**Pull request closed without merging**
