### PR TITLE
[StyleCop] Fix all the warnings in AssemblyInfo

### PR DESCRIPTION
**Pull request by Aliandi**
- Remove trailing whitespace

### CODE REVIEW

**Review by ceciliaavila — APPROVED** [review]
LGTM

**Review by VictorGrycuk — DISMISSED** [review]
:shipit:

**Comment by VictorGrycuk** [comment]
@Aliandi The PR contains changes other than the trailing spaces. The file `Definitions.csproj` contains additions, and `Definitions.xml` seems to be a new file. The title and body in the PR does not mentions changes to these files.
Could you please review this?

**Comment by Aliandi** [comment]
@VictorGrycuk I removed those files since they are at #194, just left AssemblyInfo

**Review by VictorGrycuk — APPROVED** [review]
LGTM

**Review by JuanAr — APPROVED** [review]
👍

**Pull request closed without merging**
