### PR TITLE
[StyleCop] Fix all the warnings in Chinese Parser files

### PR DESCRIPTION
**Pull request by Aliandi**
- Fixed spacing.
- Reordered using statements.

### CODE REVIEW

**Review by ceciliaavila — APPROVED** [review]
LGTM

**Review by VictorGrycuk — APPROVED** [review]
🚢 it

**Review by Bill7zz — COMMENTED** [review]
LGTM

**Review by Bill7zz — APPROVED** [review]

**Review by JuanAr — APPROVED** [review]
👍

**Pull request closed without merging**
