### PR TITLE
[StyleCop] Fix all warnings in TimexHelpers

### PR DESCRIPTION
**Pull request by Bill7zz**
- Fix spacing.
- Add trailing commas when needed.

### CODE REVIEW

**Review by Aliandi — APPROVED** [review]
LGTM

**Comment by VictorGrycuk** [comment]
Could you add a new line before the `return` in line [19](https://github.com/southworkscom/Recognizers-Text/blob/1cf7dbc6785914116a1b54d80177a99e698b157b/.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexHelpers.cs#L19) of TimexHelpers.cs?

**Review by VictorGrycuk — DISMISSED** [review]
Disregard requested changes.

**Review by VictorGrycuk — APPROVED** [review]
:shipit:

**Review by JuanAr — APPROVED** [review]
Good!

**Pull request closed without merging**
