### PR TITLE
[StyleCop] Fix all the warnings in Portuguese extractors and parsers

### PR DESCRIPTION
**Pull request by Aliandi**
- Reorder usings
- Reorder methods
- Remove extra whitespace
- Add spacing
- Change "" to string.Empty

### CODE REVIEW

**Review by ceciliaavila — CHANGES_REQUESTED** [review]
I think this class should be 'public' instead of 'internal'.
image

**Comment by Aliandi** [comment]
@ceciliaavila feedback applied

**Review by ceciliaavila — APPROVED** [review]
LGTM

**Review by JuanAr — APPROVED** [review]
LGTM

**Pull request closed without merging**
