### PR TITLE
 [StyleCop] Fix all the warnings in DataType.Tests

### PR DESCRIPTION
**Pull request by Aliandi**
- Add code analysis rule set for tests
- Add settings file
- Remove parenthesis
- Add spacing
- Add trailing comma

### CODE REVIEW

**Review by ceciliaavila — CHANGES_REQUESTED** [review]
Please, remove Settings.StyleCop file.

**Review by ceciliaavila — APPROVED** [review]
LGTM

**Review by VictorGrycuk — APPROVED** [review]
LGTM

**Review by JuanAr — APPROVED** [review]
👍

**Pull request closed without merging**
