### PR TITLE
[StyleCop] Fix all the warnings in BooleanExtractorConfiguration files.

### PR DESCRIPTION
**Pull request by Aliandi**
- Fixed spacing.
- Added trailing commas when needed.
- Added access modifier to classes.

### CODE REVIEW

**Review by VictorGrycuk — APPROVED** [review]
LGTM

**Review by ceciliaavila — APPROVED** [review]
LGTM

**Review by JuanAr — APPROVED** [review]
LGTM

**Review by JuanAr — APPROVED** [review]
Good!

**Pull request closed without merging**
