### PR TITLE
[StyleCop] Fix BaseDateExtractor StyleCop Warnings

### PR DESCRIPTION
**Pull request by JuanAr**

### CODE REVIEW

**Comment by JuanAr** [comment]
@denscollo please solve conflicts with master

**Comment by JuanAr** [comment]
@denscollo ?

**Comment by denscollo** [comment]
Will solve the issues now

**Review by ceciliaavila — APPROVED** [review]
LGTM

**Review by JuanAr — COMMENTED** [review]
👍

**Pull request closed without merging**
