### PR TITLE
[StyleCop] Fix all warnings in the Sequence tests

### PR DESCRIPTION
**Pull request by Aliandi**
- Reorder usings
- Change base to this

### CODE REVIEW

**Review by Bill7zz — APPROVED** [review]
LGTM

**Review by VictorGrycuk — CHANGES_REQUESTED** [review]
I'm having several warnings on these files. I believe it is the same issue as PR #92.

If these changes depend on change made in another PR, add a line in this PR details noting that this PR depends on another, with a link to said PR:
> **Note:** This PR depends on PR [#XXX](https://github.com/southworkscom/Recognizers-Text/pull/XXX). Will rebase when it is merged.

**Review by VictorGrycuk — APPROVED** [review]
Goood 👍

**Review by JuanAr — APPROVED** [review]
👍

**Pull request closed without merging**
